Secure, configurable anonymisation
microsoft/InnerEye-Gateway pull request #107
Opened 2022-07-19 15:49 UTC by peterhessey

Closes #79.

This PR introduces changes to how the anonymisation works in the IE-Gateway. Specifically, the DICOM tags sent to the inference service are now specified in `GatewayProcessorConfig.json` instead of `SegmenationClient.cs`, making it much simpler for users to configure their own anonymisation protocols. 

Furthermore, `PatientID` is no longer sent to the inference service by default, as it is not needed for inference.

2022-07-19 22:42 UTC, ant0nsc requested changes
Looking good, overall - you really have picked up a lot of the C# bits!
I have not been able to spot a unit test for the core functionality of converting a string tuple (name, method) to its typed counterparts? (GetSegmentationAnonymisationProtocol) Anything to do with reflection should be tested really carefully, I feel. Also, this is a user-provided file, and should be checked more thoroughly for duplicates, etc.

At the risk of distracting you: Would an alternative way of creating  the JSON config lead to shorter and easier to maintain configs?
```
{
   "Keep": ["foo", "bar"],
   "randomize": ["date"],
   "hash": ["baz"]
}
```

2022-07-19 22:42 UTC, ant0nsc commented on README.md
> +```shell
```suggestion
```text
```

2022-07-19 22:42 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Azure.Segmentation.Client/InnerEyeSegmentationClient.cs
> +                switch (dicomTagConfig["AnonymisationMethod"])
there is no error handling for key not found

2022-07-19 22:42 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Azure.Segmentation.Client/InnerEyeSegmentationClient.cs
> +                    case "Keep":
For all the 3 enum cases, should that be case insensitive?

2022-07-19 22:42 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Azure.Segmentation.Client/InnerEyeSegmentationClient.cs
> +                    if (string.Equals(field.Name, dicomTagConfig["DicomTagID"], StringComparison.Ordinal))
what if "DicomTagID" is not present?

2022-07-19 22:42 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Azure.Segmentation.Client/InnerEyeSegmentationClient.cs
> +                    throw new ArgumentException($"Unknown DicomTag found in config: {dicomTagConfig["DicomTagID"]}");
there are a lot of repeated string literals here

2022-07-19 22:42 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Gateway.Models/AnonymisationSettings.cs
> +            return other != null;  /// not sure about this! will return equal even if settings aren't the same?
I'm confused about the comment and the code

2022-07-19 22:43 UTC, ant0nsc commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Azure.Segmentation.Client/InnerEyeSegmentationClient.cs
> +                    throw new ArgumentException($"Unknown DicomTag found in config: {dicomTagConfig["DicomTagID"]}");
turn them into constants?

2022-07-20 13:52 UTC, peterhessey commented
> Looking good, overall - you really have picked up a lot of the C# bits! I have not been able to spot a unit test for the core functionality of converting a string tuple (name, method) to its typed counterparts? (GetSegmentationAnonymisationProtocol) Anything to do with reflection should be tested really carefully, I feel. Also, this is a user-provided file, and should be checked more thoroughly for duplicates, etc.
> 
> At the risk of distracting you: Would an alternative way of creating the JSON config lead to shorter and easier to maintain configs?
> 
> ```
> {
>    "Keep": ["foo", "bar"],
>    "randomize": ["date"],
>    "hash": ["baz"]
> }
> ```

I completely agree, and have updated the PR accordingly.

2022-07-27 10:56 UTC, ant0nsc approved these changes
Looking good! Just one question: What happens if someone has an existing Gateway installation, with an "old" config file, and they now use the new gateway code? Would it throw an error because there is no anonymization section?

2022-07-27 13:29 UTC, javier-alvarez approved these changes

2022-07-27 13:57 UTC, peterhessey commented on Source/Microsoft.Gateway/Microsoft.InnerEye.Gateway.Models/AnonymisationSettings.cs
> +        public bool Equals(AnonymisationSettings other) => other != null && DicomTagsAnonymisationConfig.Count == other.DicomTagsAnonymisationConfig.Count;
Good spot - had meant to come back to this as I got stuck on it. Fixed now, learning the hard way that `==` is really is not the same as in python!

2022-07-27 14:52 UTC, merged